### PR TITLE
Adds jest unit test support and 100% getStatusBarHeight method coverage tests

### PR DESCRIPTION
**Pull request by fabiodamasceno**

### CODE REVIEW

**Comment by fabiodamasceno** [comment]
Any suggestions I'm here to improve this code.

**Comment by ovr** [comment]
@fabiodamasceno Will be cool to have running tests on CI on top of GitHub Actions, are you familiar with it?

Thanks

**Comment by fabiodamasceno** [comment]
Sure, I'm used to automate CI in another tool, but it's an amazing opportunity to learn how to GH Actions works ;D

**Comment by fabiodamasceno** [comment]
Update. Github actions yaml added.

**Comment by ovr** [comment]
Merged, Thank you @fabiodamasceno 

Awesome!

**Pull request merged**
